/*Rocio García Núñez y  Lidia Barja Diez*/
--Descripcion de las tablas--
DESCRIBE pr3_countries;
DESCRIBE pr3_departments;
DESCRIBE pr3_employees;
DESCRIBE pr3_job_history;
DESCRIBE pr3_jobs;
DESCRIBE pr3_locations;
DESCRIBE pr3_regions;
---consultas sql---
--1
SELECT FIRST_NAME, LAST_NAME
FROM PR3_EMPLOYEES JOIN PR3_DEPARTMENTS USING (DEPARTMENT_ID)
WHERE DEPARTMENT_NAME = 'Finance'
ORDER BY LAST_NAME;
--2
SELECT FIRST_NAME , LAST_NAME FROM PR3_EMPLOYEES E1 JOIN PR3_DEPARTMENTS D1 ON E1.EMPLOYEE_ID = D1.MANAGER_ID;
--3
SELECT DISTINCT E2.LAST_NAME 
FROM PR3_EMPLOYEES E1 JOIN PR3_DEPARTMENTS D1 ON (E1.DEPARTMENT_ID = D1.DEPARTMENT_ID ) 
JOIN PR3_EMPLOYEES E2 ON (E2.EMPLOYEE_ID = D1.MANAGER_ID)
WHERE  E1.SALARY < E2.SALARY;
--4
SELECT DISTINCT FIRST_NAME , LAST_NAME 
FROM PR3_DEPARTMENTS D JOIN PR3_JOB_HISTORY JH ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN PR3_EMPLOYEES E1  ON JH.EMPLOYEE_ID = E1.EMPLOYEE_ID
WHERE D.DEPARTMENT_NAME = 'Sales';
--5
SELECT DISTINCT JOB_TITLE
FROM PR3_JOBS JOIN PR3_EMPLOYEES USING (JOB_ID) 
JOIN PR3_DEPARTMENTS USING (DEPARTMENT_ID)
WHERE PR3_DEPARTMENTS.DEPARTMENT_NAME = 'IT';
--6
/*SELECT DISTINCT FIRST_NAME, DEPARTMENT_NAME ,COUNTRY_NAME
FROM  PR3_EMPLOYEES E JOIN  PR3_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
JOIN PR3_LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID JOIN PR3_COUNTRIES CO ON L.COUNTRY_ID = CO.COUNTRY_ID
JOIN PR3_REGIONS R ON CO.REGION_ID = R.REGION_ID
WHERE D.DEPARTMENT_NAME LIKE '%e%' AND R.REGION_NAME <> 'Europa';*/
--7
SELECT L.LOCATION_ID,L.CITY,CO.COUNTRY_ID,D.DEPARTMENT_NAME FROM PR3_DEPARTMENTS D 
JOIN  PR3_LOCATIONS L  ON D.LOCATION_ID =L.LOCATION_ID
JOIN PR3_COUNTRIES CO ON CO.COUNTRY_ID = L.COUNTRY_ID
WHERE CO.COUNTRY_NAME = 'United Kingdom' 
  UNION 
SELECT L.LOCATION_ID,L.CITY,CO.COUNTRY_ID,NULL FROM  
PR3_LOCATIONS L JOIN PR3_COUNTRIES CO ON CO.COUNTRY_ID = L.COUNTRY_ID
WHERE CO.COUNTRY_NAME = 'United Kingdom'
ORDER BY CITY;
--8
SELECT COUNTRY_NAME FROM PR3_COUNTRIES 
MINUS
SELECT COUNTRY_NAME
FROM PR3_COUNTRIES JOIN PR3_LOCATIONS USING(COUNTRY_ID)
ORDER BY COUNTRY_NAME DESC;
--9


