DROP TABLE        pr5_customers             CASCADE CONSTRAINTS;
DROP TABLE        pr5_inventories           CASCADE CONSTRAINTS;
DROP TABLE        pr5_order_items           CASCADE CONSTRAINTS;
DROP TABLE        pr5_orders                CASCADE CONSTRAINTS;
DROP TABLE        pr5_product_descriptions  CASCADE CONSTRAINTS;
DROP TABLE        pr5_product_information   CASCADE CONSTRAINTS;
DROP TABLE        pr5_warehouses            CASCADE CONSTRAINTS;
DROP TYPE         pr5_cust_address_typ;
DROP TYPE         pr5_phone_list_typ;
DROP SEQUENCE     pr5_orders_seq;
